#!/usr/bin/env python
__author__ = 'aikikode'

WIN_WIDTH = 1440
WIN_HEIGHT = 1080
DISPLAY = (WIN_WIDTH, WIN_HEIGHT)
RIGHT_PANEL_WIDTH = 200
RIGHT_PANEL_HEIGHT = 200
LEFT_PANEL_WIDTH = 300
LEFT_PANEL_HEIGHT = 50
MAIN_WIN_WIDTH = WIN_WIDTH
MAIN_WIN_HEIGHT = WIN_HEIGHT

PLAYER1 = "yellow"
PLAYER2 = "green"

