#!/usr/bin/env python
__author__ = 'aikikode'

WIN_WIDTH = 1280
WIN_HEIGHT = 900
DISPLAY = (WIN_WIDTH, WIN_HEIGHT)
HUD_WIDTH = WIN_WIDTH
HUD_HEIGHT = 200
MAIN_WIN_WIDTH = WIN_WIDTH
MAIN_WIN_HEIGHT = WIN_HEIGHT - HUD_HEIGHT

PLAYER1 = "yellow"
PLAYER2 = "green"
